services:
  file-service:
    build:
      context: ./file_service
      dockerfile: Dockerfile
    ports:
    - "8081:8081"
    environment:
      MINIO_ENDPOINT: http://minio:${MINIO_PORT:-9000}
      MINIO_PORT: ${MINIO_PORT:-9000}
      ACCESS_KEY: ${MINIO_ACCESS_KEY}
      SECRET_KEY: ${MINIO_SECRET_KEY}
#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOST}:${KAFKA_PORT}
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_FILE}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
      - minio
      - redis
      - kafka
    networks:
      - my-network

#  config-server:
#    image: config-server
#    build:
#      context: ./config-server
#      dockerfile: Dockerfile
#    ports:
#      - "8888:8888"
#    environment:
#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOST}:${KAFKA_PORT}
#    depends_on:
#      - kafka
#    networks:
#      - my-network

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8889:8889"
    networks:
      - my-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_AUTH}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - eureka-server
    networks:
      - my-network

#  auth-service:
#    build:
#      context: ./auth-service
#      dockerfile: Dockerfile
#    ports:
#      - "8085:8085"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_AUTH}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOST}:${KAFKA_PORT}
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      ADMIN_EMAIL: ${ADMIN_EMAIL}
#      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
#    depends_on:
#      - db
#      - kafka
#    networks:
#      - my-network

  business:
    build:
      context: ./business
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_PROJECT}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      SPRING_REDIS_HOST: redis
#      SPRING_REDIS_PORT: 6379
#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOST}:${KAFKA_PORT}
    depends_on:
      - db
      - redis
      - kafka
      - elasticsearch
      - logstash
    networks:
      - my-network

#  email-service:
#    build:
#      context: ./email-service
#      dockerfile: Dockerfile
#    ports:
#      - "8083:8083"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_EMAIL}
#      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
#      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
#      MAIL_USERNAME: ${MAIL_USERNAME}
#      MAIL_PASSWORD: ${MAIL_PASSWORD}
#      MAIL_HOST: ${MAIL_HOST}
#      MAIL_PORT: ${MAIL_PORT}
#      KAFKA_BOOTSTRAP_SERVERS: ${KAFKA_HOST}:${KAFKA_PORT}
#    depends_on:
#      - db
#      - minio
#      - redis
#      - kafka
#    networks:
#      - my-network

#  camunda:
#    build:
#      context: ./camunda-service
#      dockerfile: Dockerfile
#    ports:
#      - "8086:8086"
#    depends_on:
#      - db
#      - minio
#      - redis
#      - kafka
#    networks:
#      - my-network

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    command: postgres -c 'max_connections=1000'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      my-network:

  minio:
    image: minio/minio:latest
    container_name: minio_s3
    ports:
      - "${MINIO_PORT}:${MINIO_PORT}"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin1234
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped
    networks:
      my-network:

  redis:
    image: redis:latest
    container_name: redis_service
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      my-network:

  kafka:
    image: 'bitnamilegacy/kafka:latest'
    container_name: kafka
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_BROKER_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker

      # 👇 ВАЖНО
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092

      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT

      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_KRAFT_CLUSTER_ID=D-9LSBnqTSGU6k78YpctOw

    ports:
      - "9092:9092"
      - "29092:29092"

    networks:
      my-network:

#  prometheus:
#    image: prom/prometheus
#    ports:
#      - "9090:9090"
#    volumes:
#      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  elasticsearch:
    image: elasticsearch:8.18.1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      my-network:

  logstash:
    image: logstash:8.18.1
    ports:
      - "5044:5044"
      - "9600:9600"
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
      - ./conf/postgresql-42.7.5.jar:/usr/share/logstash/postgresql-42.7.5.jar
    depends_on:
      - db
      - elasticsearch
    restart: unless-stopped
    networks:
      my-network:

volumes:
  postgres_data:
  minio_data:
  redis_data:
  kafka_data:
  elasticsearch_data:

networks:
  my-network:
    name: my-network
    driver: bridge
