server:
  port: 9201

spring:
  application:
    name: camunda-service

tasks:
  instance-key: test_bpmn
  business-key: process

kafka:
  bootstrap-server: localhost:9092
  group-id: file-service-group

topics:
  publish-event-topic: publish-event

params:
  user-id: X-user-id
  user-role: X-user-role

camunda:
  bpm:
    deployment-resource-pattern: classpath*:/processes/*.bpmn
    admin-user:
      id: camunda
      password: admin